### ISSUE TITLE
Readthedocs badge says documentation is failing

### ISSUE THREAD

**Issue by magoorden** [DEIS-Tools/strategoutil#48]
The badge says documentation is failing. Unclear yet why it is failing.

**Comment by magoorden** [comment]
> Looking like some value is missing
> 
> ```
> Error
> Config validation error in build.os. Value build not found.
> ```

Where did you find this error message?

**Comment by magoorden** [comment]
> > Looking like some value is missing
> > ```
> > Error
> > Config validation error in build.os. Value build not found.
> > ```
> 
> Where did you find this error message?

Found it at https://readthedocs.org/projects/strategoutil/builds/24681599/

**Comment by magoorden** [comment]
Readthedocs is still referring to the old GitHub repository with `git clone --depth 1 https://github.com/mihsamusev/strategoutil.git .`

**Comment by magoorden** [comment]
The build on Read The Docs now produces the following error

```
Error
At least one of the following configuration options is required: build.tools or build.commands.
```

**Comment by AshkanFeyzollahi** [comment]
happy to see that you fixed problem

**Comment by magoorden** [comment]
Yes, it's fixed. Thanks for the initial nudge in the right direction.
